name: time-series
channels:
  - defaults
dependencies:
  - python>=3.7,<3.10
  - pytorch::pytorch
  - conda-forge::jupyter
  - pip
  - pip:
    - numpy>=1.18.5,<2
    - scipy>=1.5.4,<2
    - pandas>=1.3.2,<1.4
    - scikit-learn>=0.24.2,<2
    - matplotlib>=3.1.3,<4
    - seaborn>=0.11.1,<1
